---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: loxilb-lb
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: loxilb-app
  template:
    metadata:
      name: loxilb-lb
      labels:
        app: loxilb-app
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        #- key: "node-role.kubernetes.io/master"
        #operator: Exists
      - key: "node-role.kubernetes.io/control-plane"
        operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              #- key: "node-role.kubernetes.io/master"
              #  operator: Exists
              - key: "node-role.kubernetes.io/control-plane"
                operator: Exists
      initContainers:
      - name: loxilb-mountbpf
        image: "ghcr.io/loxilb-io/loxilb:latest"
        command: ['sh', '-c', 'mkdir -p /opt/loxilb/dp/ && mount -t bpf bpf /opt/loxilb/dp/ && mv /usr/local/sbin/mkllb_bpffs /usr/local/sbin/mkllb_bpffs.bk']
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        volumeMounts:
          - name: maps
            mountPath: /opt/loxilb/dp/
            mountPropagation: Bidirectional
      containers:
      - name: loxilb-app
        image: "ghcr.io/loxilb-io/loxilb:latest"
        imagePullPolicy: Always
        #command: ['sh', '-c', 'sleep infinity']
        #command: [ "/root/loxilb-io/loxilb/loxilb", "-p", "--egr-hooks", "--blacklist=cni[0-9a-z]|veth.|flannel.|cali.|tunl.|vxlan[.]calico" ]
        command: ['sh', '-c']
        args: 
          - mv /usr/local/sbin/mkllb_bpffs /usr/local/sbin/mkllb_bpffs.bk; 
            /root/loxilb-io/loxilb/loxilb "-p" "--egr-hooks" "--blacklist=cni[0-9a-z]|veth.|flannel.|cali.|tunl.|vxlan[.]calico";
        ports:
        - containerPort: 11111
        - containerPort: 1791
        - containerPort: 50051
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        volumeMounts:
          - name: maps
            mountPath: /opt/loxilb/dp/
            mountPropagation: Bidirectional
      - name: loxiflow
        image: "docker.io/nxinho/loxiflow:latest"
        command: ['/root/loxilb-io/loxiflow/loxiflow']
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        volumeMounts:
          - name: maps
            mountPath: /opt/loxilb/dp/
            mountPropagation: HostToContainer
      restartPolicy: Always
      volumes:
        - name: maps
          hostPath:
            path: /opt/loxilb/dp/
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: loxilb-lb-service
  namespace: kube-system
spec:
  clusterIP: None
  selector:
    app: loxilb-app
  ports:
  - name: loxilb-app
    port: 11111
    targetPort: 11111
    protocol: TCP
  - name: loxilb-app-bgp
    port: 1791
    targetPort: 1791
    protocol: TCP
  - name: loxilb-app-gobgp
    port: 50051
    targetPort: 50051
    protocol: TCP